apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
  labels:
    app: converter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: rahul226/converter:latest
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
